-- Database Backup for new_ai_cabs_db
-- Generated on 2026-08-21T05:47:52.591Z

CREATE DATABASE IF NOT EXISTS `new_ai_cabs_db`;
USE `new_ai_cabs_db`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `booking`;
CREATE TABLE `booking` (
  `bookingId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `bookingDate` datetime DEFAULT NULL,
  `managerApprovalToken` text COLLATE utf8mb4_unicode_ci,
  `bookingTime` time DEFAULT NULL,
  `signature` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `employeeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `pickupPoint` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingCreatedBy` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `behalfOfName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `behalfOfPhone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupCity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupArea` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `predefinedArea` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dropPoint` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupLongitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupLatitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dropLatitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dropLongitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `travelLatitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `travelTrail` json NOT NULL,
  `travelLongitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `angle` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `travellersCount` int DEFAULT NULL,
  `femaleCount` int DEFAULT NULL,
  `maleCount` int DEFAULT NULL,
  `pickupAirport` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupStation` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approximatetds2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approximatetds1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remarks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purpose` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookingStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `driverTripStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `autoApproveStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `preferredType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `roundTrip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `paymentId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `driverId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `createdBy` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `vehicleMasterId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `costCenter` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `selfName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  `bookingType` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ORGANIZATION',
  PRIMARY KEY (`bookingId`),
  UNIQUE KEY `bookingCode` (`bookingCode`),
  UNIQUE KEY `bookingCode_2` (`bookingCode`),
  UNIQUE KEY `bookingCode_3` (`bookingCode`),
  UNIQUE KEY `bookingCode_4` (`bookingCode`),
  UNIQUE KEY `bookingCode_5` (`bookingCode`),
  UNIQUE KEY `bookingCode_6` (`bookingCode`),
  UNIQUE KEY `bookingCode_7` (`bookingCode`),
  UNIQUE KEY `bookingCode_8` (`bookingCode`),
  UNIQUE KEY `bookingCode_9` (`bookingCode`),
  UNIQUE KEY `bookingCode_10` (`bookingCode`),
  UNIQUE KEY `bookingCode_11` (`bookingCode`),
  UNIQUE KEY `bookingCode_12` (`bookingCode`),
  UNIQUE KEY `bookingCode_13` (`bookingCode`),
  KEY `vehicleId` (`vehicleId`),
  KEY `paymentId` (`paymentId`),
  KEY `vehicleTypeId` (`vehicleTypeId`),
  KEY `driverId` (`driverId`),
  KEY `vehicleMasterId` (`vehicleMasterId`),
  KEY `managerUserId` (`managerUserId`),
  KEY `companyId` (`companyId`),
  KEY `fk_booking_operator` (`operatorId`),
  KEY `userId` (`userId`),
  KEY `employeeId` (`employeeId`),
  CONSTRAINT `booking_ibfk_100` FOREIGN KEY (`userId`) REFERENCES `user` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_101` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`employeeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_14` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_16` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_23` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_25` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_32` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_34` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_41` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_43` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_5` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_50` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_52` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_59` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_61` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_68` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_7` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_70` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_77` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_79` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_86` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_88` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_93` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`vehicleId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_94` FOREIGN KEY (`paymentId`) REFERENCES `payment` (`paymentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_95` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_96` FOREIGN KEY (`driverId`) REFERENCES `drivers` (`driverId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_97` FOREIGN KEY (`vehicleMasterId`) REFERENCES `vehiclemaster` (`vehicleMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_99` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_booking_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `booking_passenger`;
CREATE TABLE `booking_passenger` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `bookingId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `passengerName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `passengerPhone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `passengerEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_booking_passenger_book` (`bookingId`),
  CONSTRAINT `fk_booking_passenger_book` FOREIGN KEY (`bookingId`) REFERENCES `booking` (`bookingId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `booking_sequence`;
CREATE TABLE `booking_sequence` (
  `seq_date` date NOT NULL,
  `last_number` int DEFAULT NULL,
  PRIMARY KEY (`seq_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `closependings`;
CREATE TABLE `closependings` (
  `closependingId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `pickupDate` datetime NOT NULL,
  `garageKms` int DEFAULT '0',
  `usageHours` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `garageOpenKm` int DEFAULT NULL,
  `garageCloseKm` int DEFAULT NULL,
  `garageOpenDateTime` datetime DEFAULT NULL,
  `garageCloseDateTime` datetime DEFAULT NULL,
  `guestKms` int DEFAULT '0',
  `guestOpenKm` int DEFAULT NULL,
  `guestCloseKm` int DEFAULT NULL,
  `guestOpenDateTime` datetime DEFAULT NULL,
  `guestCloseDateTime` datetime DEFAULT NULL,
  `hideGuestDetails` tinyint(1) DEFAULT '0',
  `packageDataId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `extraDriverBeta` decimal(10,2) DEFAULT '0.00',
  `driverBetaDays` int DEFAULT '0',
  `chargesTitle` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `chargesRemarks` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extraChargesBreakup` json DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `additionalKms` int DEFAULT '0',
  `additionalHours` int DEFAULT '0',
  `discountAmount` decimal(10,2) DEFAULT '0.00',
  `advanceAmount` decimal(10,2) DEFAULT '0.00',
  `cgstApplicable` tinyint(1) DEFAULT '0',
  `igstApplicable` tinyint(1) DEFAULT '0',
  `sgstApplicable` tinyint(1) DEFAULT '0',
  `packageAmount` decimal(10,2) DEFAULT '0.00',
  `additionalKmsAmount` decimal(10,2) DEFAULT '0.00',
  `additionalHoursAmount` decimal(10,2) DEFAULT '0.00',
  `totalAmount` decimal(10,2) DEFAULT '0.00',
  `extraCharges` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT '0.00',
  `totalDue` decimal(10,2) DEFAULT '0.00',
  `cgstAmount` decimal(10,2) DEFAULT '0.00',
  `igstAmount` decimal(10,2) DEFAULT '0.00',
  `sgstAmount` decimal(10,2) DEFAULT '0.00',
  `totalTaxAmount` decimal(10,2) DEFAULT '0.00',
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `tripSheetNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `selectedPackageData` json DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`closependingId`),
  KEY `packageDataId` (`packageDataId`),
  CONSTRAINT `closependings_ibfk_1` FOREIGN KEY (`packageDataId`) REFERENCES `packagedata` (`packageDataId`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `company`;
CREATE TABLE `company` (
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `companyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyPhno` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `employeeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `domainName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `seoUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gstNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerEmail` text COLLATE utf8mb4_unicode_ci,
  `managerApproval` tinyint(1) DEFAULT '0',
  `allowTax` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `needEmail` tinyint(1) DEFAULT '0',
  `companyLogo` text COLLATE utf8mb4_unicode_ci,
  `companyAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `closeTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priorMinutes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDeleted` tinyint(1) DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`companyId`),
  KEY `userId` (`userId`),
  KEY `employeeId` (`employeeId`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `company_ibfk_23` FOREIGN KEY (`userId`) REFERENCES `user` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `company_ibfk_24` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`employeeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `company_ibfk_25` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `configuration`;
CREATE TABLE `configuration` (
  `configId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `serviceTaxPercentage` float DEFAULT NULL,
  `dueDays` int DEFAULT NULL,
  `invoiceNoStartingFrom` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cancelBookingHours` int DEFAULT NULL,
  `invoiceNoPrefix` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpServer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpEmailAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpEmailPassword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpEmailPort` int DEFAULT NULL,
  `outstationHasTax` tinyint(1) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`configId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `drivers`;
CREATE TABLE `drivers` (
  `driverId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `driverName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `driverEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phno` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pincode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `licenseNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `licExpDate` datetime DEFAULT NULL,
  `otp` int DEFAULT NULL,
  `ratings` int DEFAULT NULL,
  `trackLocation` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trackingsource` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcm_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `createdBy` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`driverId`),
  UNIQUE KEY `phno` (`phno`),
  UNIQUE KEY `phno_2` (`phno`),
  UNIQUE KEY `phno_3` (`phno`),
  UNIQUE KEY `phno_4` (`phno`),
  UNIQUE KEY `phno_5` (`phno`),
  UNIQUE KEY `phno_6` (`phno`),
  UNIQUE KEY `phno_7` (`phno`),
  UNIQUE KEY `phno_8` (`phno`),
  UNIQUE KEY `phno_9` (`phno`),
  UNIQUE KEY `phno_10` (`phno`),
  UNIQUE KEY `phno_11` (`phno`),
  UNIQUE KEY `phno_12` (`phno`),
  UNIQUE KEY `phno_13` (`phno`),
  KEY `vehicleId` (`vehicleId`),
  KEY `vehicleTypeId` (`vehicleTypeId`),
  KEY `createdBy` (`createdBy`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `drivers_ibfk_11` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_14` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_17` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_2` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_20` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_23` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_26` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_29` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_32` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_34` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`vehicleId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_35` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_36` FOREIGN KEY (`createdBy`) REFERENCES `employee` (`employeeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_37` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_5` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `drivers_ibfk_8` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `emailconfiguration`;
CREATE TABLE `emailconfiguration` (
  `emailConfigId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emailCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message` longtext COLLATE utf8mb4_unicode_ci,
  `fromName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fromAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emailBcc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`emailConfigId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `employee`;
CREATE TABLE `employee` (
  `employeeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `empManager` tinyint(1) DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phno` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcm_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`employeeId`),
  UNIQUE KEY `phno` (`phno`),
  UNIQUE KEY `phno_2` (`phno`),
  UNIQUE KEY `phno_3` (`phno`),
  UNIQUE KEY `phno_4` (`phno`),
  UNIQUE KEY `phno_5` (`phno`),
  UNIQUE KEY `phno_6` (`phno`),
  UNIQUE KEY `phno_7` (`phno`),
  UNIQUE KEY `phno_8` (`phno`),
  UNIQUE KEY `phno_9` (`phno`),
  UNIQUE KEY `phno_10` (`phno`),
  UNIQUE KEY `phno_11` (`phno`),
  UNIQUE KEY `phno_12` (`phno`),
  UNIQUE KEY `phno_13` (`phno`),
  UNIQUE KEY `phno_14` (`phno`),
  UNIQUE KEY `phno_15` (`phno`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `employee_ibfk_1` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `employee` VALUES 
('af4a9245-912d-4fa2-b78f-d4303a41befb', 'Platform Admin', NULL, 'admin@fleet.local', '9000000001', '$2b$12$zAvDYa7mxvb3zJeOZwCI1.UhrMb3xdsLCa8WrWhs/U5XQcs9m.eT2', 'superadmin', NULL, '2026-08-20 06:03:27', 'oper-0001-0000-0000-000000000001');

DROP TABLE IF EXISTS `fleet_operator`;
CREATE TABLE `fleet_operator` (
  `operatorId` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `operatorName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contactEmail` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contactPhone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`operatorId`),
  UNIQUE KEY `operator_email_unique` (`contactEmail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `fleet_operator` VALUES 
('oper-0001-0000-0000-000000000001', 'Fleet Operations HQ', 'operator@fleet.local', '9000000000', 'active', '2026-08-20 11:30:10', '2026-08-20 11:30:10');

DROP TABLE IF EXISTS `invoice`;
CREATE TABLE `invoice` (
  `invoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `invoiceNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startDate` datetime DEFAULT NULL,
  `endDate` datetime DEFAULT NULL,
  `invoiceAmount` int DEFAULT NULL,
  `userId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `vendorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `invoiceStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bookingId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `closePendingId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `paymentId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `monthlyInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`invoiceId`),
  UNIQUE KEY `invoiceNumber` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_2` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_3` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_4` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_5` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_6` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_7` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_8` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_9` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_10` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_11` (`invoiceNumber`),
  UNIQUE KEY `invoiceNumber_12` (`invoiceNumber`),
  KEY `userId` (`userId`),
  KEY `vendorId` (`vendorId`),
  KEY `vehicleTypeId` (`vehicleTypeId`),
  KEY `bookingId` (`bookingId`),
  KEY `closePendingId` (`closePendingId`),
  KEY `companyId` (`companyId`),
  KEY `paymentId` (`paymentId`),
  KEY `monthlyInvoiceId` (`monthlyInvoiceId`),
  KEY `fk_invoice_operator` (`operatorId`),
  CONSTRAINT `fk_invoice_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_11` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_19` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_27` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_3` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_35` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_43` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_51` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_59` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_67` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_75` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_81` FOREIGN KEY (`userId`) REFERENCES `user` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_82` FOREIGN KEY (`vendorId`) REFERENCES `vendor` (`vendorId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_83` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_84` FOREIGN KEY (`bookingId`) REFERENCES `booking` (`bookingId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_85` FOREIGN KEY (`closePendingId`) REFERENCES `closependings` (`closependingId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_86` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_87` FOREIGN KEY (`paymentId`) REFERENCES `payment` (`paymentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `invoice_ibfk_88` FOREIGN KEY (`monthlyInvoiceId`) REFERENCES `monthly_invoice` (`monthlyInvoiceId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `invoice_sequences`;
CREATE TABLE `invoice_sequences` (
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `financialYear` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `current` int DEFAULT '0',
  PRIMARY KEY (`companyId`,`financialYear`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `mapcount`;
CREATE TABLE `mapcount` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `appCount` int DEFAULT '0',
  `webCount` int DEFAULT '0',
  `isDeleted` tinyint(1) DEFAULT '0',
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `monthly_invoice`;
CREATE TABLE `monthly_invoice` (
  `monthlyInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `monthlyBookingCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoiceDate` date NOT NULL,
  `invoiceMonth` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `companyName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vehicleTypeName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vehicleNumber` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `route` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `packageDataId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `packageDetails` json DEFAULT NULL,
  `extraKm` double NOT NULL DEFAULT '0',
  `extraDays` double NOT NULL DEFAULT '0',
  `extraChargeType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'toll',
  `extraChargesInputAmount` double NOT NULL DEFAULT '0',
  `discount` double NOT NULL DEFAULT '0',
  `advance` double NOT NULL DEFAULT '0',
  `packageAmount` double NOT NULL DEFAULT '0',
  `extraKmAmount` double NOT NULL DEFAULT '0',
  `extraDaysAmount` double NOT NULL DEFAULT '0',
  `extraHrs` double NOT NULL DEFAULT '0',
  `extraHourRate` double NOT NULL DEFAULT '0',
  `extraHrsAmount` double NOT NULL DEFAULT '0',
  `netTotal` double NOT NULL DEFAULT '0',
  `extraCharges` json DEFAULT NULL,
  `taxes` json DEFAULT NULL,
  `totalTaxAmount` double NOT NULL DEFAULT '0',
  `finalTotal` double NOT NULL DEFAULT '0',
  `closeStatus` int NOT NULL DEFAULT '0',
  `invoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `balanceDue` double NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`monthlyInvoiceId`),
  UNIQUE KEY `monthlyBookingCode` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_2` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_3` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_4` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_5` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_6` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_7` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_8` (`monthlyBookingCode`),
  UNIQUE KEY `monthlyBookingCode_9` (`monthlyBookingCode`),
  KEY `companyId` (`companyId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `fk_monthly_invoice_operator` (`operatorId`),
  CONSTRAINT `fk_monthly_invoice_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `monthly_invoice_ibfk_15` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `monthly_invoice_ibfk_16` FOREIGN KEY (`invoiceId`) REFERENCES `invoice` (`invoiceId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `monthly_invoice_items`;
CREATE TABLE `monthly_invoice_items` (
  `monthlyInvoiceItemId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `monthlyInvoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `route` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `vehicleTypeName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `packageDataId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `packageDetails` json DEFAULT NULL,
  `packageAmount` double NOT NULL DEFAULT '0',
  `extraKm` double NOT NULL DEFAULT '0',
  `extraKmAmount` double NOT NULL DEFAULT '0',
  `extraDays` double NOT NULL DEFAULT '0',
  `extraDaysAmount` double NOT NULL DEFAULT '0',
  `extraHrs` double NOT NULL DEFAULT '0',
  `extraHourRate` double NOT NULL DEFAULT '0',
  `extraHrsAmount` double NOT NULL DEFAULT '0',
  `extraChargeType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'toll',
  `extraChargesInputAmount` double NOT NULL DEFAULT '0',
  `extraCharges` json DEFAULT NULL,
  `discount` double NOT NULL DEFAULT '0',
  `advance` double NOT NULL DEFAULT '0',
  `netTotal` double NOT NULL DEFAULT '0',
  `taxes` json DEFAULT NULL,
  `totalTaxAmount` double NOT NULL DEFAULT '0',
  `finalTotal` double NOT NULL DEFAULT '0',
  `balanceDue` double NOT NULL DEFAULT '0',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`monthlyInvoiceItemId`),
  KEY `monthlyInvoiceId` (`monthlyInvoiceId`),
  CONSTRAINT `monthly_invoice_items_ibfk_1` FOREIGN KEY (`monthlyInvoiceId`) REFERENCES `monthly_invoice` (`monthlyInvoiceId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `monthlybookingsequence`;
CREATE TABLE `monthlybookingsequence` (
  `financialYear` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyCode` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastNumber` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`financialYear`,`companyCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `oncallinvoice`;
CREATE TABLE `oncallinvoice` (
  `onCallBillId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `onCallInvoiceCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `companyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tripSheetNumbers` text COLLATE utf8mb4_unicode_ci,
  `totalAmount` decimal(18,2) DEFAULT NULL,
  `totalTaxAmount` text COLLATE utf8mb4_unicode_ci,
  `invoiceSubTotal` decimal(18,2) DEFAULT NULL,
  `invoiceTaxBreakup` text COLLATE utf8mb4_unicode_ci,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`onCallBillId`),
  UNIQUE KEY `onCallInvoiceCode` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_2` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_3` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_4` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_5` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_6` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_7` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_8` (`onCallInvoiceCode`),
  UNIQUE KEY `onCallInvoiceCode_9` (`onCallInvoiceCode`),
  KEY `companyId` (`companyId`),
  KEY `fk_oncallinvoice_operator` (`operatorId`),
  CONSTRAINT `fk_oncallinvoice_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoice_ibfk_1` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `oncallinvoiceitems`;
CREATE TABLE `oncallinvoiceitems` (
  `onCallInvoiceItemId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `onCallBillId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `tripSheetNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `vehicleTypeId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `driverName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guestName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bookedBy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tripDetails` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `garageOpenKm` float DEFAULT NULL,
  `garageCloseKm` float DEFAULT NULL,
  `garageKms` float DEFAULT NULL,
  `guestOpenKm` float DEFAULT NULL,
  `guestCloseKm` float DEFAULT NULL,
  `guestKms` float DEFAULT NULL,
  `hideGuestDetails` tinyint(1) DEFAULT NULL,
  `startingTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `closingTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usageHours` float DEFAULT NULL,
  `packageType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `travelPackage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `packageDays` int DEFAULT NULL,
  `driverDays` int DEFAULT NULL,
  `selectedPackageMeta` text COLLATE utf8mb4_unicode_ci,
  `packageAmount` decimal(18,2) DEFAULT NULL,
  `additionalKms` float DEFAULT NULL,
  `additionalKmsAmount` decimal(18,2) DEFAULT NULL,
  `additionalHours` float DEFAULT NULL,
  `additionalHoursAmount` decimal(18,2) DEFAULT NULL,
  `driverBatta` decimal(18,2) DEFAULT NULL,
  `extraChargesBreakup` text COLLATE utf8mb4_unicode_ci,
  `extraCharges` decimal(18,2) DEFAULT NULL,
  `discountAmount` decimal(18,2) DEFAULT NULL,
  `advanceAmount` decimal(18,2) DEFAULT NULL,
  `taxes` text COLLATE utf8mb4_unicode_ci,
  `totalTaxAmount` decimal(18,2) DEFAULT NULL,
  `amount` decimal(18,2) DEFAULT NULL,
  `total` decimal(18,2) DEFAULT NULL,
  `totalDue` decimal(18,2) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`onCallInvoiceItemId`),
  KEY `onCallBillId` (`onCallBillId`),
  CONSTRAINT `oncallinvoiceitems_ibfk_1` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_2` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_3` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_4` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_5` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_6` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_7` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oncallinvoiceitems_ibfk_8` FOREIGN KEY (`onCallBillId`) REFERENCES `oncallinvoice` (`onCallBillId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `ordersummery`;
CREATE TABLE `ordersummery` (
  `ordersummeryid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `invoiceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `taxId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`ordersummeryid`),
  KEY `companyId` (`companyId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `taxId` (`taxId`),
  CONSTRAINT `ordersummery_ibfk_22` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ordersummery_ibfk_23` FOREIGN KEY (`invoiceId`) REFERENCES `invoice` (`invoiceId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ordersummery_ibfk_24` FOREIGN KEY (`taxId`) REFERENCES `tax` (`taxId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `organization_package`;
CREATE TABLE `organization_package` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `packageId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `customBaseAmount` decimal(10,2) DEFAULT NULL,
  `customExtraKmRate` decimal(10,2) DEFAULT NULL,
  `customExtraHourRate` decimal(10,2) DEFAULT NULL,
  `effectiveDate` date DEFAULT NULL,
  `expiryDate` date DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_org_package_operator` (`operatorId`),
  KEY `fk_org_package_company` (`companyId`),
  KEY `fk_org_package_pack` (`packageId`),
  CONSTRAINT `fk_org_package_company` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_org_package_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_org_package_pack` FOREIGN KEY (`packageId`) REFERENCES `package` (`packageId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `otp`;
CREATE TABLE `otp` (
  `otpId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `otp` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `loginId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `sessionId` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expiresAt` datetime NOT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`otpId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `package`;
CREATE TABLE `package` (
  `packageId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `packageType` enum('Out Station','Local City Use') COLLATE utf8mb4_unicode_ci NOT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`packageId`),
  KEY `companyId` (`companyId`),
  KEY `fk_package_operator` (`operatorId`),
  CONSTRAINT `fk_package_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_ibfk_1` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `packagedata`;
CREATE TABLE `packagedata` (
  `packageDataId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `packageType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `packages` longtext COLLATE utf8mb4_unicode_ci,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`packageDataId`),
  KEY `companyId` (`companyId`),
  KEY `fk_packagedata_operator` (`operatorId`),
  CONSTRAINT `fk_packagedata_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `packagedata_ibfk_1` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `partners`;
CREATE TABLE `partners` (
  `partnerId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contactNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `presentAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cityPreferred` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `licenseNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registrationNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registrationYear` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fuelType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `passengerCapacity` int DEFAULT NULL,
  `isDeleted` tinyint(1) DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`partnerId`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `contactNumber` (`contactNumber`),
  UNIQUE KEY `licenseNo` (`licenseNo`),
  UNIQUE KEY `registrationNumber` (`registrationNumber`),
  UNIQUE KEY `email_2` (`email`),
  UNIQUE KEY `contactNumber_2` (`contactNumber`),
  UNIQUE KEY `licenseNo_2` (`licenseNo`),
  UNIQUE KEY `registrationNumber_2` (`registrationNumber`),
  UNIQUE KEY `email_3` (`email`),
  UNIQUE KEY `contactNumber_3` (`contactNumber`),
  UNIQUE KEY `licenseNo_3` (`licenseNo`),
  UNIQUE KEY `registrationNumber_3` (`registrationNumber`),
  UNIQUE KEY `email_4` (`email`),
  UNIQUE KEY `contactNumber_4` (`contactNumber`),
  UNIQUE KEY `licenseNo_4` (`licenseNo`),
  UNIQUE KEY `registrationNumber_4` (`registrationNumber`),
  UNIQUE KEY `email_5` (`email`),
  UNIQUE KEY `contactNumber_5` (`contactNumber`),
  UNIQUE KEY `licenseNo_5` (`licenseNo`),
  UNIQUE KEY `registrationNumber_5` (`registrationNumber`),
  UNIQUE KEY `email_6` (`email`),
  UNIQUE KEY `contactNumber_6` (`contactNumber`),
  UNIQUE KEY `licenseNo_6` (`licenseNo`),
  UNIQUE KEY `registrationNumber_6` (`registrationNumber`),
  UNIQUE KEY `email_7` (`email`),
  UNIQUE KEY `contactNumber_7` (`contactNumber`),
  UNIQUE KEY `licenseNo_7` (`licenseNo`),
  UNIQUE KEY `registrationNumber_7` (`registrationNumber`),
  UNIQUE KEY `email_8` (`email`),
  UNIQUE KEY `contactNumber_8` (`contactNumber`),
  UNIQUE KEY `licenseNo_8` (`licenseNo`),
  UNIQUE KEY `registrationNumber_8` (`registrationNumber`),
  UNIQUE KEY `email_9` (`email`),
  UNIQUE KEY `contactNumber_9` (`contactNumber`),
  UNIQUE KEY `licenseNo_9` (`licenseNo`),
  UNIQUE KEY `registrationNumber_9` (`registrationNumber`),
  UNIQUE KEY `email_10` (`email`),
  UNIQUE KEY `contactNumber_10` (`contactNumber`),
  UNIQUE KEY `licenseNo_10` (`licenseNo`),
  UNIQUE KEY `registrationNumber_10` (`registrationNumber`),
  UNIQUE KEY `email_11` (`email`),
  UNIQUE KEY `contactNumber_11` (`contactNumber`),
  UNIQUE KEY `licenseNo_11` (`licenseNo`),
  UNIQUE KEY `registrationNumber_11` (`registrationNumber`),
  UNIQUE KEY `email_12` (`email`),
  UNIQUE KEY `contactNumber_12` (`contactNumber`),
  UNIQUE KEY `licenseNo_12` (`licenseNo`),
  UNIQUE KEY `registrationNumber_12` (`registrationNumber`),
  KEY `fk_partners_operator` (`operatorId`),
  CONSTRAINT `fk_partners_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payment`;
CREATE TABLE `payment` (
  `paymentId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `paymentMode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `transactionId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(10,0) DEFAULT NULL,
  `tax` decimal(10,0) DEFAULT NULL,
  `orderId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gatewayOrderId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paymentUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clientAuthToken` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expiresAt` datetime DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`paymentId`),
  UNIQUE KEY `transactionId` (`transactionId`),
  UNIQUE KEY `transactionId_2` (`transactionId`),
  UNIQUE KEY `transactionId_3` (`transactionId`),
  UNIQUE KEY `transactionId_4` (`transactionId`),
  UNIQUE KEY `transactionId_5` (`transactionId`),
  UNIQUE KEY `transactionId_6` (`transactionId`),
  UNIQUE KEY `transactionId_7` (`transactionId`),
  UNIQUE KEY `transactionId_8` (`transactionId`),
  UNIQUE KEY `transactionId_9` (`transactionId`),
  UNIQUE KEY `transactionId_10` (`transactionId`),
  UNIQUE KEY `transactionId_11` (`transactionId`),
  UNIQUE KEY `transactionId_12` (`transactionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payment_sequence`;
CREATE TABLE `payment_sequence` (
  `seq_date` date NOT NULL,
  `last_number` int DEFAULT NULL,
  PRIMARY KEY (`seq_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `paymentmode`;
CREATE TABLE `paymentmode` (
  `paymentmodeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `modelname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sortorder` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`paymentmodeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `pickuparea`;
CREATE TABLE `pickuparea` (
  `areaId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `pickupCity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupArea` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`areaId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `pickupcity`;
CREATE TABLE `pickupcity` (
  `cityId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `country` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickupCity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sortOrder` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isPickupCity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`cityId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `schedules`;
CREATE TABLE `schedules` (
  `scheduleId` char(36) NOT NULL,
  `scheduleName` varchar(255) NOT NULL,
  `operatorId` char(36) DEFAULT NULL,
  `organizationId` char(36) NOT NULL,
  `pickupLocation` text NOT NULL,
  `dropLocation` text NOT NULL,
  `days` varchar(100) DEFAULT NULL,
  `pickupTime` time DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `vehicleTypeId` char(36) DEFAULT NULL,
  `passengerCount` int DEFAULT '1',
  `notes` text,
  `status` varchar(50) DEFAULT 'active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`scheduleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `short_links`;
CREATE TABLE `short_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullUrl` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime DEFAULT NULL,
  `expiresAt` datetime DEFAULT NULL COMMENT 'If set, short link expires at this time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `short_links_code` (`code`),
  UNIQUE KEY `code_2` (`code`),
  UNIQUE KEY `code_3` (`code`),
  UNIQUE KEY `code_4` (`code`),
  UNIQUE KEY `code_5` (`code`),
  UNIQUE KEY `code_6` (`code`),
  UNIQUE KEY `code_7` (`code`),
  UNIQUE KEY `code_8` (`code`),
  UNIQUE KEY `code_9` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tax`;
CREATE TABLE `tax` (
  `taxId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `taxName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `taxPercent` double DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`taxId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `userId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `danfossuserId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isManager` tinyint(1) DEFAULT NULL,
  `companyManager` tinyint(1) DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approvedManagerById` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` enum('male','female','other') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcm_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companyId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `status` enum('active','inactive','suspended','pending') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `presentAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pinCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isPayHolder` tinyint(1) NOT NULL DEFAULT '0',
  `costCenter` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `isConfirmed` tinyint(1) NOT NULL DEFAULT '0',
  `addresses` json DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`userId`),
  KEY `companyId` (`companyId`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`companyId`) REFERENCES `company` (`companyId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `user_ibfk_2` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vehicle`;
CREATE TABLE `vehicle` (
  `vehicleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vehicleName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `manufacturing` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vehicleImg` json DEFAULT NULL,
  `availableStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`vehicleId`),
  KEY `vehicleTypeId` (`vehicleTypeId`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `vehicle_ibfk_1` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_10` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_11` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_12` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_13` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_2` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_3` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_4` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_5` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_6` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_7` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_8` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE,
  CONSTRAINT `vehicle_ibfk_9` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vehiclemaster`;
CREATE TABLE `vehiclemaster` (
  `vehicleMasterId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vehicleNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vehicleModelName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `vehicleType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vendorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vendorName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `isDeleted` int DEFAULT '0',
  `deletedAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`vehicleMasterId`),
  KEY `vehicleId` (`vehicleId`),
  KEY `vehicleTypeId` (`vehicleTypeId`),
  KEY `vendorId` (`vendorId`),
  KEY `fk_vehiclemaster_operator` (`operatorId`),
  CONSTRAINT `fk_vehiclemaster_operator` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_11` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_14` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_17` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_2` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_20` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_23` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_25` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_27` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_28` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`vehicleId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_29` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_30` FOREIGN KEY (`vendorId`) REFERENCES `vendor` (`vendorId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_5` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehiclemaster_ibfk_8` FOREIGN KEY (`vehicleTypeId`) REFERENCES `vehicletype` (`vehicleTypeId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vehicletype`;
CREATE TABLE `vehicletype` (
  `vehicleTypeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vehicleType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleImg` json DEFAULT NULL,
  `AdvanceBookingHours` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `seatCapacity` int DEFAULT NULL,
  `priorMinutes` int NOT NULL DEFAULT '0',
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `bookingType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'regular',
  `createdAt` datetime DEFAULT NULL,
  PRIMARY KEY (`vehicleTypeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vendor`;
CREATE TABLE `vendor` (
  `vendorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vendorName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcm_token` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phno` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vehicleCount` int DEFAULT NULL,
  `refererVendor` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdBy` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime DEFAULT NULL,
  `operatorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'e111111d-2e65-4d7a-85d1-125035feee1a',
  PRIMARY KEY (`vendorId`),
  UNIQUE KEY `phno` (`phno`),
  UNIQUE KEY `phno_2` (`phno`),
  UNIQUE KEY `phno_3` (`phno`),
  UNIQUE KEY `phno_4` (`phno`),
  UNIQUE KEY `phno_5` (`phno`),
  UNIQUE KEY `phno_6` (`phno`),
  UNIQUE KEY `phno_7` (`phno`),
  UNIQUE KEY `phno_8` (`phno`),
  UNIQUE KEY `phno_9` (`phno`),
  UNIQUE KEY `phno_10` (`phno`),
  UNIQUE KEY `phno_11` (`phno`),
  UNIQUE KEY `phno_12` (`phno`),
  UNIQUE KEY `phno_13` (`phno`),
  KEY `createdBy` (`createdBy`),
  KEY `operatorId` (`operatorId`),
  CONSTRAINT `vendor_ibfk_1` FOREIGN KEY (`createdBy`) REFERENCES `employee` (`employeeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vendor_ibfk_2` FOREIGN KEY (`operatorId`) REFERENCES `fleet_operator` (`operatorId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
